### ISSUE TITLE
My final suggestions

### ISSUE THREAD

**Issue by willbmisled** [USEPA/LakeTrophicModelling#19]
Review and delete my notes in the body of the text

- [x] Figure 1: color code dots by Trophic State?

- [x] Figures 4 & 7: add ug/l to the y-label or mention in caption. What about the units on the X axis.  Alternatively, all units could be specified in the appendix.

- [x] Figures 7 and 13-need to add the names of the ecoregions since they are mentioned in the text.  Alternatively they could be shown in a new table or in the body of text.

- [x] Figures 8 & 9: need legend or specify in caption All Var=Red and GIS=Black

- [x] Figure 9: is the Y axis label term "conditional total accuracy" defined in the text?

- [x] Figure 10: the subpanels (maps),need to be larger.  Consider using the same color scale for all and Figure 11 also.

- [x] Table 1:  add ug/l to the column heading "concentration cut-off"

- [ ] Tables 2 & 3 add the "Predicted" over column labels and "Observed" next to row labels.

- [x] Appendix: add units and summary stats column-Mean and SE if not more.

**Comment by jhollist** [comment]
Leaving table 2 and 3 as is with predicted and observed described in caption.  Issue with pandoc tables makes this non-trivial.

**Comment by jhollist** [comment]
All done except Tables 2 and 3 as described above.
