### ISSUE TITLE
DOI?

### ISSUE THREAD

**Issue by benmarwick** [USEPA/LakeTrophicModelling#27]
Would it be possible for you to deposit this repo at zenodo or figshare or similar so it can get a DOI? I want to cite it in a paper (as a shining example of using R pkgs as research compendia) and would prefer to have a DOI specifically for this repo (rather than the publication) for the authoritative version of the code. Thanks!

**Comment by jhollist** [comment]
It has been.  Just forgot to add it to the README!!

[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.40271.svg)](http://dx.doi.org/10.5281/zenodo.40271)

and published paper is:

Hollister, J. W., W. B . Milstead, B. J. Kreakie. (2016). Modeling Lake Trophic State: A Random Forest Approach. Ecosphere 7:3 10.1002/ecs2.1321.

**Comment by benmarwick** [comment]
Perfect, thanks very much!
